#arquivo yaml
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: marina
  name: marina-2
spec:
  containers:
  - image: nginx
    name: marina
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
